-- Datos nuevos

INSERT INTO Jobs (ID, ubicacion, posicion, compañia, fecha, categoria, tipo, logo, descripcion) VALUES
(1,'Paris', 'Tester', 'Google', '2020-01-10', 'Web','Full Time','http://brandemia.org/sites/default/files/logo_google_nuevo_portada.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus consectetur ac leo vel posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut bibendum nibh, sit amet tincidunt purus. Maecenas sit amet justo eget lorem sodales aliquam vitae eu massa. Suspendisse fringilla massa ante, a sodales ex tincidunt vel. Etiam in commodo urna. Aenean non auctor leo. Etiam dolor libero, vehicula id sollicitudin et, pharetra quis eros. Nullam non facilisis diam, sit amet luctus quam. Nulla facilisi. Nunc lectus dui, pharetra ut ultricies egestas, condimentum ut orci. Donec id consequat metus. Pellentesque in vulputate quam, quis fermentum ligula. Sed tincidunt porttitor quam, vitae pellentesque diam. Donec rutrum sem odio, ut egestas leo commodo vitae.

Donec tortor odio, tincidunt nec aliquet nec, tempor in velit. Morbi lectus arcu, porttitor eu hendrerit a, finibus non lectus. Nunc ac turpis quam. Nunc ipsum nunc, volutpat nec porttitor sit amet, auctor at ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam eu volutpat nisl. Cras ut congue tellus. Nulla vel lacus facilisis, elementum erat vitae, lobortis velit. Vivamus ligula nunc, rhoncus eu nisl nec, bibendum bibendum diam. Nam placerat venenatis dolor vehicula hendrerit. Sed eleifend gravida eros. Donec vehicula, velit non ullamcorper ornare, metus quam congue eros, et mollis nisl purus vitae dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;'),
(2,'Jamaica', 'Debugger', 'Apple Inc', '2020-02-14','Backend','Freelancer','https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/1200px-Apple_logo_black.svg.png','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus consectetur ac leo vel posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut bibendum nibh, sit amet tincidunt purus. Maecenas sit amet justo eget lorem sodales aliquam vitae eu massa. Suspendisse fringilla massa ante, a sodales ex tincidunt vel. Etiam in commodo urna. Aenean non auctor leo. Etiam dolor libero, vehicula id sollicitudin et, pharetra quis eros. Nullam non facilisis diam, sit amet luctus quam. Nulla facilisi. Nunc lectus dui, pharetra ut ultricies egestas, condimentum ut orci. Donec id consequat metus. Pellentesque in vulputate quam, quis fermentum ligula. Sed tincidunt porttitor quam, vitae pellentesque diam. Donec rutrum sem odio, ut egestas leo commodo vitae.

Donec tortor odio, tincidunt nec aliquet nec, tempor in velit. Morbi lectus arcu, porttitor eu hendrerit a, finibus non lectus. Nunc ac turpis quam. Nunc ipsum nunc, volutpat nec porttitor sit amet, auctor at ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam eu volutpat nisl. Cras ut congue tellus. Nulla vel lacus facilisis, elementum erat vitae, lobortis velit. Vivamus ligula nunc, rhoncus eu nisl nec, bibendum bibendum diam. Nam placerat venenatis dolor vehicula hendrerit. Sed eleifend gravida eros. Donec vehicula, velit non ullamcorper ornare, metus quam congue eros, et mollis nisl purus vitae dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;'),
(3,'Londres', 'Developer', 'Sony', '2020-03-08', 'Desktop','Full Time','https://logos-marcas.com/wp-content/uploads/2020/04/Sony-Logo.png','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus consectetur ac leo vel posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut bibendum nibh, sit amet tincidunt purus. Maecenas sit amet justo eget lorem sodales aliquam vitae eu massa. Suspendisse fringilla massa ante, a sodales ex tincidunt vel. Etiam in commodo urna. Aenean non auctor leo. Etiam dolor libero, vehicula id sollicitudin et, pharetra quis eros. Nullam non facilisis diam, sit amet luctus quam. Nulla facilisi. Nunc lectus dui, pharetra ut ultricies egestas, condimentum ut orci. Donec id consequat metus. Pellentesque in vulputate quam, quis fermentum ligula. Sed tincidunt porttitor quam, vitae pellentesque diam. Donec rutrum sem odio, ut egestas leo commodo vitae.

Donec tortor odio, tincidunt nec aliquet nec, tempor in velit. Morbi lectus arcu, porttitor eu hendrerit a, finibus non lectus. Nunc ac turpis quam. Nunc ipsum nunc, volutpat nec porttitor sit amet, auctor at ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam eu volutpat nisl. Cras ut congue tellus. Nulla vel lacus facilisis, elementum erat vitae, lobortis velit. Vivamus ligula nunc, rhoncus eu nisl nec, bibendum bibendum diam. Nam placerat venenatis dolor vehicula hendrerit. Sed eleifend gravida eros. Donec vehicula, velit non ullamcorper ornare, metus quam congue eros, et mollis nisl purus vitae dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;'),
(4,'Los Angeles', 'Web Security', 'Haweii','2020-04-15', 'Web','Freelancer','https://lh3.googleusercontent.com/proxy/KjNQ8evZ4RbJiwTBxeHrAhZIWeornzzknM9A-p5m_qGE7_PofWtl3JV1UghxXRrzYMnpFJ3BMIa6sQSRpIgGtKfCQIp12kA-FC57prbYDqDqAe4tWCM','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus consectetur ac leo vel posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut bibendum nibh, sit amet tincidunt purus. Maecenas sit amet justo eget lorem sodales aliquam vitae eu massa. Suspendisse fringilla massa ante, a sodales ex tincidunt vel. Etiam in commodo urna. Aenean non auctor leo. Etiam dolor libero, vehicula id sollicitudin et, pharetra quis eros. Nullam non facilisis diam, sit amet luctus quam. Nulla facilisi. Nunc lectus dui, pharetra ut ultricies egestas, condimentum ut orci. Donec id consequat metus. Pellentesque in vulputate quam, quis fermentum ligula. Sed tincidunt porttitor quam, vitae pellentesque diam. Donec rutrum sem odio, ut egestas leo commodo vitae.

Donec tortor odio, tincidunt nec aliquet nec, tempor in velit. Morbi lectus arcu, porttitor eu hendrerit a, finibus non lectus. Nunc ac turpis quam. Nunc ipsum nunc, volutpat nec porttitor sit amet, auctor at ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam eu volutpat nisl. Cras ut congue tellus. Nulla vel lacus facilisis, elementum erat vitae, lobortis velit. Vivamus ligula nunc, rhoncus eu nisl nec, bibendum bibendum diam. Nam placerat venenatis dolor vehicula hendrerit. Sed eleifend gravida eros. Donec vehicula, velit non ullamcorper ornare, metus quam congue eros, et mollis nisl purus vitae dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;'),
(5,'España', 'Web Designer', 'Google', '2020-01-10', 'Web','Part Time','http://brandemia.org/sites/default/files/logo_google_nuevo_portada.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus consectetur ac leo vel posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ut bibendum nibh, sit amet tincidunt purus. Maecenas sit amet justo eget lorem sodales aliquam vitae eu massa. Suspendisse fringilla massa ante, a sodales ex tincidunt vel. Etiam in commodo urna. Aenean non auctor leo. Etiam dolor libero, vehicula id sollicitudin et, pharetra quis eros. Nullam non facilisis diam, sit amet luctus quam. Nulla facilisi. Nunc lectus dui, pharetra ut ultricies egestas, condimentum ut orci. Donec id consequat metus. Pellentesque in vulputate quam, quis fermentum ligula. Sed tincidunt porttitor quam, vitae pellentesque diam. Donec rutrum sem odio, ut egestas leo commodo vitae.

Donec tortor odio, tincidunt nec aliquet nec, tempor in velit. Morbi lectus arcu, porttitor eu hendrerit a, finibus non lectus. Nunc ac turpis quam. Nunc ipsum nunc, volutpat nec porttitor sit amet, auctor at ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam eu volutpat nisl. Cras ut congue tellus. Nulla vel lacus facilisis, elementum erat vitae, lobortis velit. Vivamus ligula nunc, rhoncus eu nisl nec, bibendum bibendum diam. Nam placerat venenatis dolor vehicula hendrerit. Sed eleifend gravida eros. Donec vehicula, velit non ullamcorper ornare, metus quam congue eros, et mollis nisl purus vitae dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;');